--liquibase formatted sql

--changeset Dauren:1
--comment first_migration

create table account(
                        id int PRIMARY KEY generated by default as identity,
                        balance numeric,
                        currency_shortname varchar(5),
                        limit_sum numeric default 1000,
                        limit_datetime timestamp default now(),
                        limit_currency_shortname varchar(3) default 'USD',
                        current_limit_sum numeric default 1000
);
create table transaction(
                            id int primary key generated by default as identity,
                            account_from int references account(id) on delete set null ,
                            account_to int references account(id) on delete set null ,
                            currency_shortname varchar(5),
                            sum numeric,
                            expense_category varchar(30),
                            transaction_date timestamp default now(),
                            limit_exceeded boolean
);
create table exchange_rate(
                              id int primary key generated by default as identity,
                              tng_usd numeric,
                              rub_usd numeric,
                              closeDate timestamp default now()
);